Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-05, with the labels that each got.

#1007 Feat: update electron
  package-lock.json
  package.json
Labels: doc not required, ui not required

#1012 Feat: show depreciation warning
  src/ipc/persistedStore.ts
  src/launcher/Root.tsx
  src/launcher/features/appleSilicon/AppleSiliconAlert.tsx
  src/launcher/features/appleSilicon/AppleSiliconDialog.tsx
  src/launcher/features/appleSilicon/appleSiliconEffects.ts
  src/launcher/features/appleSilicon/appleSiliconSlice.ts
  src/launcher/features/quickstart/QuickstartDialog.tsx
  src/launcher/store.ts
Labels: doc required, ui required

#1009 doc: non_mkdocs: move proxy guide, delete rest
  doc/docs/download_cfd.md
  doc/docs/installing_apps.md
  doc/docs/proxy_settings.md
  doc/docs/screenshots/proxy-login-dialog.png
  doc/mkdocs.yml
  doc/non_mkdocs/proxy-login-dialog.png
  doc/non_mkdocs/proxy-settings.md
  doc/non_mkdocs/repeated-usb-address-troubleshoot.md
  doc/non_mkdocs/serial-timeout-troubleshoot.md
  doc/non_mkdocs/win32-drivers-installing.png
  doc/non_mkdocs/win32-drivers-ready.png
  doc/non_mkdocs/win32-usb-troubleshoot.md
  doc/non_mkdocs/win32-usbtree-expected.png
Labels: documentation, doc required

#1010 Display publish date for non-official sources
  Changelog.minor.md
  package-lock.json
  package.json
  src/launcher/features/apps/App/App.tsx
  src/launcher/util/formatTimestamp.ts
  src/main/apps/appBundler.ts
  src/main/apps/appChanges.ts
Labels: doc not required, ui not required

#1013 Release 5.0.0: changelog update
  Changelog.md
Labels: doc not required, ui not required
