Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-02, with the labels that each got.

#964 fix: update shared with updated packagejson types to remove error
  package-lock.json
  package.json
Labels: doc not required

#962 Release 4.4.0 prepare
  .github/workflows/build_darwin_arm64.yml
  Changelog.md
  Changelog.minor.md
  package-lock.json
  package.json
Labels: doc not required

#966 Fix/resend opt out
  package-lock.json
  package.json
  src/launcher/features/telemetry/telemetryEffects.ts
Labels: doc not required

#969 Fix: call function
  src/launcher/features/telemetry/telemetryEffects.ts
Labels: doc not required

#971 fix: update shared to remove overflow handling in dialogs (issue with…
  package-lock.json
  package.json
Labels: doc not required

#972 Fix: save state to file
  src/launcher/features/telemetry/telemetryEffects.ts
Labels: doc not required

#974 Release 4.4.0: update changelog date
  Changelog.md
Labels: doc not required

#978 Fix: Check if app is truly installed befare reading package.json
  Changelog.minor.md
  src/main/apps/legacyMetaFiles.ts
Labels: doc not required, ui not required

#976 feat: increase jlink version
  src/main/bundledJlinkVersion.js
Labels: doc not required, ui not required

#979 doc: update os support table
  doc/docs/os_support.md
Labels: documentation, doc required

#980 doc: os support: fix phrasing
  doc/docs/os_support.md
Labels: documentation, doc required

#981 feat: update jlink version in nsis installer
  build/installer.nsh
Labels: doc not required, ui not required
