Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-07, with the labels that each got.

#1027 Feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#1023 fix: having spaces in electron path now doesn't make path unusable
  Changelog.md
  src/main/apps/createDesktopShortcut.ts
Labels: doc required, ui not required

#1029 Update installer script: always trigger JLink install for this version
  Changelog.md
  build/installer.nsh
Labels: doc not required, ui not required

#1028 doc: update links for RSSI Viewer and nPM apps
  doc/docs/index.md
Labels: documentation, doc required

#1030 Fix: issue from older nrfutil core
  Changelog.md
  package-lock.json
  package.json
  src/main/nrfutilModules.ts
Labels: doc required, ui not required
