Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-01, with the labels that each got.

#935 Enhance message when installing downloadable apps fails
  Changelog.minor.md
  jest.config.js
  package-lock.json
  package.json
  src/launcher/features/apps/appsEffects.ts
  src/launcher/features/launcherUpdate/__snapshots__/UpdateAvailableDialog.test.tsx.snap
  src/launcher/features/launcherUpdate/__snapshots__/UpdateProgressDialog.test.tsx.snap
  src/launcher/features/proxyLogin/__snapshots__/ProxyErrorDialog.test.tsx.snap
  src/launcher/features/proxyLogin/__snapshots__/ProxyLoginDialog.test.tsx.snap
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/sources/__snapshots__/ConfirmRemoveSourceDialog.test.tsx.snap
Labels: doc-required

#939 All PRs require doc_* label
  .github/workflows/labels.yml
Labels: doc not required

#947 Test/is yq there
  .github/workflows/release.yml
  scripts/mergeLatestYmls.js
Labels: doc not required

#949 Experiment with label action
  .github/workflows/labels.yml
Labels: doc not required

#952 Rename `usageData` → `telemetry`
  src/launcher/Root.tsx
  src/launcher/features/apps/appsEffects.ts
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/quickstart/QuickstartDialog.tsx
  src/launcher/features/settings/Settings.tsx
  src/launcher/features/telemetry/TelemetryDialog.tsx
  src/launcher/features/telemetry/telemetryEffects.ts
  src/launcher/features/telemetry/telemetrySlice.ts
  src/launcher/features/usageData/usageDataEffects.ts
  src/launcher/features/usageData/usageDataSlice.ts
  src/launcher/store.ts
  src/launcher/util/ErrorBoundaryLauncher.tsx
  src/launcher/util/registerIpcHandler.ts
Labels: doc not required

#954 Renovate: Set `doc not required` label for PRs
  .github/renovate.json
Labels: doc not required

#946 Add GitHub Actions to build launcher
  .github/actions/build-action/action.yml
  .github/actions/publish-action/action.yml
  .github/workflows/build.yml
  .github/workflows/build_darwin_arm64.yml
  .github/workflows/build_darwin_x64.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_win.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  build/notarize.js
  package-lock.json
  package.json
  pipelines/build.yml
  pipelines/package/darwin.yml
  pipelines/package/darwin_arm.yml
  pipelines/package/linux.yml
  pipelines/package/package.yml
  pipelines/package/windows.yml
  pipelines/pipeline.yml
  pipelines/prepare.yml
Labels: doc not required

#956 Minor changelog and Label checker
  .github/workflows/labels.yml
  Changelog.minor.md
Labels: doc not required

#957 Feat: add archiver dependency
  package-lock.json
  package.json
Labels: doc not required

#958 Feat: update electron version
  package-lock.json
  package.json
Labels: doc not required

#953 doc: add app list and generic info
  README.md
  doc/docs/download_cfd.md
  doc/docs/index.md
  doc/docs/installing_apps.md
  doc/docs/os_support.md
  doc/docs/overview_cfd.md
  doc/docs/screenshots/cfd_overview.png
  doc/docs/screenshots/cfd_overview_install.png
  doc/mkdocs.yml
  src/launcher/features/about/About.tsx
Labels: documentation, doc required

#960 feat: remove archiver dependency
  package-lock.json
  package.json
Labels: doc not required

#961 Test/security
  Changelog.md
  build/entitlements.mac.plist
Labels: doc not required
