Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-10, with the labels that each got.

#1025 doc: requirements: add libfuse2
  doc/docs/download_cfd.md
Labels: documentation

#1040 Feat/update jlink 94i
  Changelog.md
  build/installer.nsh
  package.json
Labels: doc not required, ui not required

#1041 Update to 94i
  src/main/bundledJlinkVersion.js
Labels: doc not required, ui not required

#1044 Fix: J-Link update to 7.94i
  Changelog.md
  doc/docs/download_cfd.md
Labels: documentation, ui not required

#1047 feat: remove mention of supported devices is quickstart dialog
  src/launcher/features/quickstart/QuickstartDialog.tsx
Labels: doc not required, ui not required

#1046 Update shared to 188
  Changelog.md
  package-lock.json
  package.json
  src/main/menu.ts
Labels: doc required, ui not required

#1042 Feat/jlink warning
  Changelog.md
  src/launcher/features/apps/App/AppIcon.tsx
  src/launcher/features/apps/App/OpenApp.tsx
  src/launcher/features/apps/AppList.test.tsx
  src/launcher/features/apps/ConfirmLaunchDialog.tsx
  src/launcher/features/apps/appDialogsSlice.test.ts
  src/launcher/features/apps/appDialogsSlice.ts
  src/launcher/features/apps/appsEffects.ts
  src/launcher/features/quickstart/QuickstartDialog.tsx
  src/launcher/features/telemetry/telemetryEffects.ts
  src/launcher/util/Link.tsx
  src/launcher/util/appCompatibilityWarning.test.ts
  src/launcher/util/appCompatibilityWarning.ts
  src/launcher/util/appCompatibilityWarning.tsx
  src/launcher/util/jlinkVersion.test.ts
  src/launcher/util/jlinkVersion.ts
Labels: doc required, ui required

#1049 Update app version; update min app versions required; JLink install on a Windows is conditional again
  build/installer.nsh
  package-lock.json
  package.json
  src/launcher/util/minimalRequiredAppVersions.ts
Labels: doc not required, ui not required

#1050 Fix: Drag and Drop
  src/launcher/features/localAppInstall/DropZoneForLocalApps.test.tsx
  src/launcher/features/localAppInstall/DropZoneForLocalApps.tsx
Labels: doc not required, ui not required

#1051 Fix `nrfutil` always being overwritten
  Changelog.minor.md
  src/main/configureElectronApp.ts
Labels: doc not required, ui not required

#1052 Fix to also warn for nrfutil-device 2.7
  src/launcher/util/appCompatibilityWarning.tsx
Labels: doc not required, ui not required
