Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2024-03, with the labels that each got.

#985 Release 4.4.1: prepare changelog
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#990 feat: support the shared confirm before close in restart case
  src/main/windows.ts
Labels: doc not required, ui not required

#989 Fix: Strange source URLs could be handled wrong
  Changelog.minor.md
  src/launcher/features/settings/Settings.tsx
  src/main/apps/sourceChanges.ts
  src/main/apps/sources.ts
Labels: doc not required, ui not required

#992 Release 4.4.1: edit changelog
  Changelog.md
Labels: doc required, ui not required

#997 Fix: Broken link to the proxy settings docs
  Changelog.minor.md
  doc/docs/download_cfd.md
Labels: documentation, ui not required
