Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2025-03, with the labels that each got.

#1083 Show warnings on missing token for restricted sources
  Changelog.md
  Changelog.minor.md
  src/common/persistedStore.ts
  src/launcher/Root.tsx
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/settingsEffects.ts
  src/launcher/features/sources/AddLegacySourceWarning.tsx
  src/launcher/features/sources/AddSourceDialog.tsx
  src/launcher/features/sources/DeprecatedSourcesDialog.tsx
  src/launcher/features/sources/MissingTokenWarning.tsx
  src/launcher/features/sources/sourcesEffects.ts
  src/launcher/features/sources/sourcesSlice.ts
  src/launcher/features/telemetry/telemetryEffects.ts
Labels: doc required, ui required

#1084 Refactor: Split up `sources.ts`
  src/main/apps/app.ts
  src/main/apps/appChanges.ts
  src/main/apps/apps.ts
  src/main/apps/dataMigration/legacyMetaFiles.ts
  src/main/apps/dataMigration/migrateSourcesJson.ts
  src/main/apps/dataMigration/migrateSourcesVersionedJson.test.ts
  src/main/apps/dataMigration/migrateSourcesVersionedJson.ts
  src/main/apps/dataMigration/sourcesVersionedJsonV1.ts
  src/main/apps/sources.ts
  src/main/apps/sources/sourceChanges.ts
  src/main/apps/sources/sourceJson.ts
  src/main/apps/sources/sources.ts
  src/main/apps/sources/sourcesVersionedJson.ts
  src/main/apps/sources/withdrawnJson.test.ts
  src/main/apps/sources/withdrawnJson.ts
  src/main/configureElectronApp.ts
  src/main/registerIpcHandler.ts
Labels: doc not required, ui not required

#1085 Use Chinese app server
  Changelog.md
  src/common/persistedStore.ts
  src/launcher/features/settings/Cards/AppSources.tsx
  src/launcher/features/settings/Cards/ArtifactoryToken.tsx
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/launcher/features/settings/Cards/Updates.tsx
  src/launcher/features/settings/Cards/UsageStatistics.tsx
  src/launcher/features/settings/Settings.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/settings/settingsSlice.ts
  src/main/net.ts
Labels: doc required, ui required

#1086 Bump version number
  package.json
Labels: doc not required, ui not required

#1087 Do not restrict the PR triggers to the main branch
  .github/workflows/build.yml
  .github/workflows/labels.yml
Labels: doc not required, ui not required

#1091 Change wording of Chinese app server setting
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
Labels: doc required, ui required

#1090 Feature/azure trusted signing
  .github/workflows/build_win.yml
  Changelog.md
  build/winSign.js
  package-lock.json
  package.json
Labels: doc not required, ui not required

#1093 doc: deprecate the TCM app
  doc/docs/index.md
Labels: documentation

#1094 doc: add link to the latest VSC/CLI install page
  doc/docs/index.md
Labels: documentation

#1095 doc: os_support: Update table
  doc/docs/os_support.md
Labels: documentation

#1096 Update naming according to advice from legal
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
Labels: doc required, ui required
