Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2025-09, with the labels that each got.

#1180 Create a generic process concept
  package-lock.json
  package.json
  src/common/sources.ts
  src/ipc/apps.ts
  src/launcher/features/apps/AppListEmpty.tsx
  src/launcher/features/jlinkUpdate/JLinkUpdateDialog.tsx
  src/launcher/features/jlinkUpdate/JLinkUpdateProgressDialog.tsx
  src/launcher/features/jlinkUpdate/jlinkUpdateEffects.ts
  src/launcher/features/jlinkUpdate/jlinkUpdateSlice.ts
  src/launcher/features/launcherUpdate/UpdateAvailableDialog.tsx
  src/launcher/features/launcherUpdate/launcherUpdateEffects.ts
  src/launcher/features/process/initialiseLauncher.ts
  src/launcher/features/process/thunkProcess.ts
  src/launcher/features/process/updateProcess.ts
  src/launcher/features/settings/Cards/Updates.tsx
  src/launcher/features/sources/DeprecatedSourcesDialog.tsx
  src/launcher/features/sources/MissingTokenWarning.tsx
  src/launcher/features/sources/sourcesEffects.ts
  src/launcher/features/telemetry/TelemetryDialog.tsx
  src/launcher/features/telemetry/telemetryEffects.ts
  src/launcher/index.tsx
  src/launcher/util/appCompatibilityWarning.tsx
  src/main/apps/apps.ts
  src/main/apps/dataMigration/sourcesVersionedJsonV1.ts
  src/main/apps/sources/sources.ts
  src/main/argv.ts
  src/main/registerIpcHandler.ts
  test-e2e/launcher/basicBehaviour.spec.ts
  test-e2e/launcher/installingApps.spec.ts
  test-e2e/setupTestApp.ts
Labels: doc not required, ui not required

#1182 doc: tokens: mention safeStorage
  doc/docs/revision_history.md
  doc/docs/working_with_authentications_tokens.md
Labels: documentation

#1186 doc: installation: J-Link legacy drivers
  doc/docs/download_cfd.md
  doc/docs/revision_history.md
  doc/mkdocs.yml
Labels: documentation, doc required

#1190 Fix J-Link detection on macOS
  package-lock.json
  package.json
Labels: doc not required, ui not required

#1193 Update electron-devtools-installer
  Changelog.minor.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#1196 Download arch specific variant of nrfutil
  Changelog.minor.md
  scripts/getNrfutil.js
Labels: doc not required, ui not required
