Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2025-01, with the labels that each got.

#1066 Artifactory tokens
  Changelog.minor.md
  src/ipc/artifactoryToken.ts
  src/ipc/persistedStore.ts
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/releaseNotes/ReleaseNotesDialog.tsx
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Settings.test.tsx
  src/launcher/features/settings/Settings.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/settings/settingsSlice.ts
  src/launcher/features/sources/AddSourceDialog.tsx
  src/main/artifactoryToken.ts
  src/main/artifactoryTokenStorage.ts
  src/main/net.ts
  src/main/registerIpcHandler.ts
Labels: doc required, ui required

#1067 doc: add application source code section
  doc/docs/index.md
Labels: documentation, doc required

#1069 Add versioning to sources.json
  package-lock.json
  package.json
  src/launcher/features/settings/Settings.tsx
  src/main/apps/apps.ts
  src/main/apps/dataMigration/legacyMetaFiles.test.ts
  src/main/apps/dataMigration/legacyMetaFiles.ts
  src/main/apps/dataMigration/migrateSourcesJson.test.ts
  src/main/apps/dataMigration/migrateSourcesJson.ts
  src/main/apps/sourceChanges.ts
  src/main/apps/sources.test.ts
  src/main/apps/sources.ts
  src/main/fileUtil.ts
  src/main/index.ts
Labels: doc not required, ui not required

#1071 Small cleanups
  Changelog.minor.md
  package-lock.json
  package.json
  src/launcher/features/apps/AppListEmpty.tsx
  src/launcher/features/apps/__snapshots__/AppList.test.tsx.snap
  src/launcher/features/proxyLogin/ProxyErrorDialog.tsx
  src/launcher/features/proxyLogin/__snapshots__/ProxyErrorDialog.test.tsx.snap
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Settings.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/util/Link.tsx
  src/launcher/util/appCompatibilityWarning.tsx
  src/main/apps/appChanges.ts
  src/main/apps/apps.ts
  src/main/apps/sources.ts
  src/main/net.ts
Labels: doc not required, ui not required
