Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2025-06, with the labels that each got.

#1122 Remove usage of fs-extra
  Changelog.minor.md
  package-lock.json
  package.json
  src/launcher/features/apps/appsEffects.ts
  src/main/apps/app.ts
  src/main/apps/appBundler.ts
  src/main/apps/appChanges.ts
  src/main/apps/createDesktopShortcut.ts
  src/main/apps/dataMigration/legacyMetaFiles.ts
  src/main/apps/dataMigration/migrateSourcesJson.ts
  src/main/apps/dataMigration/sourcesVersionedJsonV1.ts
  src/main/apps/sources/sourceChanges.ts
  src/main/apps/sources/sourceJson.ts
  src/main/apps/sources/sources.ts
  src/main/apps/sources/sourcesVersionedJson.ts
  src/main/configureElectronApp.ts
  src/main/fileUtil.ts
  src/main/net.ts
  src/main/setUserDataDir.ts
  test-e2e/launcher/appList.spec.ts
  test-e2e/launcher/installingApps.spec.ts
  test-e2e/setupTestApp.ts
Labels: doc not required, ui not required

#1123 Fix: Asynchronicity of `openFile` and `openUrl`
  Changelog.minor.md
  src/main/open.ts
Labels: doc not required, ui not required

#1125 Specify core version of nrfutil
  Changelog.minor.md
  build/bundleApps.js
  package-lock.json
  package.json
  src/launcher/util/appCompatibilityWarning.tsx
  src/main/apps/app.ts
  src/main/apps/appChanges.ts
  src/main/nrfutilModules.ts
Labels: doc not required, ui not required

#1140 doc: identity token: align header
  doc/docs/overview_cfd.md
  doc/mkdocs.yml
Labels: documentation, ui not required

#1143 Remove obsolete Azure pipeline file
  azure-pipelines.yml
Labels: doc not required, ui not required

#1127 Shorten workflow names
  .github/actions/build-action/action.yml
  .github/workflows/build.yml
  .github/workflows/build_darwin_arm64.yml
  .github/workflows/build_darwin_x64.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_win.yml
Labels: doc not required, ui not required

#1126 Use Artifactory for auto-updating the launcher
  Changelog.md
  package.json
  src/ipc/launcherUpdate.ts
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/main/launcherUpdate.ts
  src/main/registerIpcHandler.ts
Labels: doc required, ui not required

#1133 Rewrote network code to use the fetch API
  Changelog.minor.md
  src/common/legacySource.ts
  src/common/sources.ts
  src/main/apps/appChanges.ts
  src/main/net.ts
Labels: doc not required, ui not required

#1134 Collect knowledge on Artifactory URLs
  Changelog.minor.md
  src/common/artifactoryUrl.test.ts
  src/common/artifactoryUrl.ts
  src/common/legacySource.ts
  src/common/sources.ts
  src/launcher/features/sources/sourcesEffects.ts
  src/launcher/features/sources/sourcesSlice.ts
  src/main/apps/sources/sources.ts
  src/main/net.ts
Labels: doc not required, ui not required

#1149 Cleanup build workflow
  .github/actions/publish-action/action.yml
  .github/workflows/build.yml
  .github/workflows/build_darwin.yml
  .github/workflows/build_darwin_arm64.yml
  .github/workflows/build_linux.yml
  .github/workflows/build_win.yml
  .github/workflows/release.yml
  Changelog.minor.md
Labels: doc not required, ui not required
