Repository NordicSemiconductor/pc-nrfconnect-launcher, pull requests merged in 2025-04, with the labels that each got.

#1099 Support simpler Artifactory URLs
  build/bundleApps.js
  src/common/legacySource.test.ts
  src/common/legacySource.ts
  src/launcher/features/sources/sourcesEffects.ts
  src/main/apps/dataMigration/migrateSourcesVersionedJson.test.ts
  src/main/apps/sources/sources.ts
  src/main/net.test.ts
  src/main/net.ts
Labels: doc not required, ui not required

#1101 feat: update jlink version
  Changelog.minor.md
  build/installer.nsh
  doc/docs/download_cfd.md
  src/main/bundledJlinkVersion.js
Labels: doc required, ui not required

#1102 Enhance UX around removing tokens
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Cards/Authentication.tsx
  src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Settings.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/settings/settingsSlice.ts
  src/launcher/features/sources/MissingTokenWarning.tsx
Labels: doc required, ui required

#1104 Release 5.2.0: add JLink entry to the changelog
  Changelog.md
Labels: doc required, ui not required

#1106 Artifactory: Update missing token warning
  src/common/legacySource.ts
  src/common/persistedStore.ts
  src/common/sources.ts
  src/ipc/sources.ts
  src/launcher/features/apps/App/App.tsx
  src/launcher/features/apps/appsSlice.ts
  src/launcher/features/filter/filterSlice.ts
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/settings/Cards/AppSources.tsx
  src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx
  src/launcher/features/sources/MissingTokenWarning.tsx
  src/launcher/features/sources/sourcesEffects.ts
  src/launcher/features/sources/sourcesSlice.ts
  src/main/apps/app.ts
  src/main/apps/appResource.ts
  src/main/apps/apps.ts
  src/main/apps/createDesktopShortcut.ts
  src/main/apps/dataMigration/legacyMetaFiles.ts
  src/main/apps/sources/sourceChanges.ts
  src/main/apps/sources/sourceJson.ts
  src/main/apps/sources/sources.ts
  src/main/apps/sources/sourcesVersionedJson.ts
  src/main/apps/sources/withdrawnJson.ts
  src/main/argv.ts
  src/main/config.ts
  src/main/windows.ts
  src/test/testFixtures.tsx
Labels: doc required, ui required

#1105 doc: update overview and add authentication guide
  doc/docs/overview_cfd.md
  doc/docs/screenshots/authentication_token.png
  doc/docs/screenshots/jfrog_user_profile.png
  doc/docs/working_with_authentications_tokens.md
  doc/mkdocs.yml
Labels: documentation

#1110 Do not use token for public resources
  src/main/net.ts
Labels: doc not required, ui not required

#1112 Ignore empty token
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
Labels: doc not required, ui not required

#1108 Small enhancements to the 5.2.0 wording adjustments
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Cards/Authentication.tsx
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/sources/AddLegacySourceWarning.tsx
  src/launcher/features/sources/MissingTokenWarning.tsx
Labels: doc required, ui required

#1115 Min width of launcher was much too small
  src/main/browser.ts
  src/main/windows.ts
Labels: doc not required, ui required

#1107 Release 5.2.0: wording adjustments
  src/launcher/features/settings/AddArtifactoryTokenDialog.tsx
  src/launcher/features/settings/Cards/Authentication.tsx
  src/launcher/features/settings/Cards/ChineseAppServer.tsx
  src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
  src/launcher/features/sources/AddLegacySourceWarning.tsx
  src/launcher/features/sources/DeprecatedSourcesDialog.tsx
  src/launcher/features/sources/MissingTokenWarning.tsx
Labels: doc not required, ui not required

#1117 Fix snapshots for 5.2.0
  src/launcher/features/settings/__snapshots__/Settings.test.tsx.snap
Labels: doc not required, ui not required

#1118 Fix: Asking for token for deprecated sources
  src/common/sources.ts
  src/launcher/features/initialisation/initialiseLauncherState.ts
  src/launcher/features/settings/RemoveArtifactoryTokenDialog.tsx
  src/launcher/features/sources/DeprecatedSourcesDialog.tsx
  src/launcher/features/sources/sourcesSlice.ts
  src/main/apps/sources/sources.ts
Labels: doc required, ui required

#1119 Fix: Migrating sources
  src/common/legacySource.test.ts
  src/common/legacySource.ts
  src/main/net.ts
Labels: doc not required, ui not required

#1121 Harden against future broken nrfutils
  src/main/configureElectronApp.ts
Labels: doc not required, ui not required
